// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./src/layout/Lo.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Lo: typeof import('./src/layout/Lo.vue')['default']
    LoHeader: typeof import('./src/layout/LoHeader.vue')['default']
    ReButton: typeof import('./src/components/global/ReButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
